# Generated by Django 4.0.4 on 2022-10-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_slide_id_slide_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='lecture',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classes.lecture'),
            preserve_default=False,
        ),
    ]
