# Generated by Django 4.0.4 on 2022-10-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_assignment_id_assignment_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='course',
            new_name='courses',
        ),
    ]
